<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Context\" />
    <Folder Include="Extensions\" />
    <Folder Include="Migrations\" />
    <Folder Include="Repositories\" />
    <Folder Include="Seed\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\CQRS.ProductManagement.Application.csproj" />
    <ProjectReference Include="..\Domain\CQRS.ProductManagement.Domain.csproj" />
  </ItemGroup>

</Project>
